spring:
  datasource:
    url: jdbc:h2:file:./bank_accounts_db
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    hibernate:
      ddl-auto: update

logging:
  file:
    name: application.log

app:
  currencies: RUB, USD, EUR
  document-types: passport_ru, passport_by
